### ISSUE TITLE
Split stack checks

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-go#16]
Some RISC-V implementations will be more dependent on static branch prediction.  We can be friendlier to them by moving the `morestack` call to the end of the function, so that the initial `ld; bgeu` is a not-taken forward branch.  Look at what `cmd/internal/obj/x86.stacksplit` is doing, there are subtleties with pcdata and stack adjustment that need to be handled to keep GC happy (just copying the original x86 commit is not enough).

**Comment by josharian** [comment]
It would probably be easier to copy pcdata/spadj code from arm or mips or another architecture with a link register.

**Comment by josharian** [comment]
cc @cherrymui

**Comment by prattmic** [comment]
All issues should be re-opened upstream if still relevant (unlikely).
