### ISSUE TITLE
Assorted code review cleanups

### ISSUE THREAD

**Issue by josharian** [riscv/riscv-go#18]
As part of an effort to get @sorear's changes in, so we can all move forward, I'm going to note some codereview items here that can be reasonably done as follow-up changes instead of blocking submission.

**Comment by josharian** [comment]
https://review.gerrithub.io/#/c/352837/4/src/cmd/compile/internal/riscv/ggen.go@80

**Comment by josharian** [comment]
Consider reverting https://review.gerrithub.io/#/c/352798/ if it proves to be unnecessary once everything is fully up and running.

**Comment by josharian** [comment]
Revisit the design questions and TODO in https://review.gerrithub.io/#/c/352823/.

**Comment by josharian** [comment]
cc @cherrymui

**Comment by prattmic** [comment]
All issues should be re-opened upstream if still relevant (unlikely).
