### ISSUE TITLE
The status of this port

### ISSUE THREAD

**Issue by NonerKao** [riscv/riscv-go#19]
Hi, 

I notice that this repo hasn't been updated for a while, and wonder what the porting progress into mainline is?

Actually I have a patch, aiming at completing the missing relocation types in current `src/debug/elf/elf.go`.  But I am still trying to figure out the usage of GerritHub. :)

Thanks.

**Comment by sorear** [comment]
It works, can compile itself, passes all tests, and has decent generated code quality.  I was unwell for most of 2017 and the others had their own conflicts so this hasn't been worked on recently; presumably the next step is to update it from 1.8½ to 1.10, add the missing features (cgo and external linking, mostly), and then submit it for upstreaming.  Upstreaming has already been agreed in principle.

**Comment by josharian** [comment]
The other missing pieces for upstreaming are builders and committed maintainers. (I actually suspect external linking and maybe even cgo could be omitted for an initial upstreaming.)

There’s been resistance in the past to qemu builders, and even with qemu there’d be some infrastructure to build.

And at the moment it’s not clear to me who the committed maintainers would be. I don’t have the bandwidth for unpaid work at the moment and probably won’t for quite some time. Sorry. :(

**Comment by josharian** [comment]
This port is being upstreamed. It will hopefully be available as part of Go 1.14.
