### ISSUE TITLE
cmd/internal/obj/riscv: allow From3 to be nil

### ISSUE THREAD

**Issue by josharian** [riscv/riscv-go#2]
progedit starts with:

``` go
    // Ensure everything has a From3 to eliminate a ton of nil-pointer
    // checks later.
    if p.From3 == nil {
        p.From3 = &obj.Addr{Type: obj.TYPE_NONE}
    }
```

Past experience suggests that it's worth deal with the nil checks on From3 and avoiding the allocations, as a matter of performance.

**Comment by josharian** [comment]
cc @cherrymui

**Comment by prattmic** [comment]
All issues should be re-opened upstream if still relevant (unlikely).
