### ISSUE TITLE
Build not working on Go 1.10

### ISSUE THREAD

**Issue by Immortalin** [riscv/riscv-go#20]
### What version of Go are you using (`go version`)?
go version go1.10.3 linux/amd64

### What operating system and processor architecture are you using (`go env`)?
Ubuntu 18.04 GOARCH="amd64"

### What did you do?

Follow quick start instructions: `./make.bash`

### What did you see instead?

`# runtime/internal/sys
compile: unknown architecture "riscv"`

**Comment by josharian** [comment]
This port is being upstreamed; this issue should be resolved as part of that.
