### ISSUE TITLE
Does riscv-go support bare metal?

### ISSUE THREAD

**Issue by GingerMoon** [riscv/riscv-go#21]
Dear community, 

We want to build go programes for riscv, but we want it to run on bare metal.
However I am not able to find any document specifying explicitly whether bare metal (without OS) is supported or not.
Any reply would be much appreciated!

Best Regards,
Xiang

**Comment by josharian** [comment]
This port is incomplete and relies on a very old base version of the Go toolchain. As it currently stands, I advise against using it. Please follow https://github.com/golang/go/issues/27532 for updates.

To answer your original question: no. This port currently assumes Linux.

**Comment by GingerMoon** [comment]
Thanks a log for the reply!
