### ISSUE TITLE
archive this repo, point people towards main go repo

### ISSUE THREAD

**Issue by josharian** [riscv/riscv-go#22]
this repo is now outdated. the port is being upstreamed in 1.14. we should update the readme prominently to tell people that and then archive this repo.

i don't have any permissions in this repo. i can't even close issues that i've answered. :(

so I guess @bbarenblat or @prattmic will have to do this.

**Comment by prattmic** [comment]
I'm super excited that this is finally getting upstreamed. Will everything be fully merged in 1.14? I've noticed lots of changes going in recently, which surprised me given how close the release is.

**Comment by josharian** [comment]
I think it'll be mostly functional in 1.14, but missing some things like cgo, async pre-empt. And it'll be experimental, so there are opportunities to fix things (like assembly syntax) over the next release.
