### ISSUE TITLE
Compilation of RISC-V target (CMake) is no more possible, after an update in libgo. Problems with matching arch. definition files

### ISSUE THREAD

**Issue by advancedwebdeveloper** [riscv/riscv-go#24]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Not sure. Transition between pre-1.15 (uncertain) and 1.15.

### What operating system and processor architecture are you using (`go env`)?

Host compiler (Clang) is on x86_64 Ubuntu

### What did you do?

Nothing spectacular. Just tried to compile [https://go.googlesource.com/gollvm/](https://go.googlesource.com/gollvm/) - and it is no more compiling, after some files where removed, for libgo project.

I am not claiming that there where some direct support of RISC-V arch (gollvm language front-end wasn't ever compiled for running on RISC-V). However LLVM's backend could support it (I was able to generate debug and release builds, for that) and running llvm-goc, on Linux, could potentially target RISC-V arch.

### What did you expect to see?

build.ninja would be generated.

### What did you see instead?

CMake exit with an error.

Here is my detailed explanation: [https://github.com/golang/go/issues/40528](https://github.com/golang/go/issues/40528) . 
I don't think that the maintainers of that project has any bandwidth to deal with RISC-V support - so you might help with that.

Ivan

**Comment by sorear** [comment]
this repository has nothing to do with GoLLVM

**Comment by josharian** [comment]
@prattmic this repository should probably be archived now. Want to do the honors?

**Comment by prattmic** [comment]
@advancedwebdeveloper https://github.com/golang/go/issues/40528 looks like the right place for this.

@josharian will do.
