### ISSUE TITLE
cmd/asm: add convenience pseudo instructions

### ISSUE THREAD

**Issue by josharian** [riscv/riscv-go#4]
- A real NOP (`ADD $0, ZERO, ZERO`), not the plan9 pseudo-op NOP. What should it be called?
- SEQZ (`SLTIU rs, $1, rd`) and friends. Have to decide whether to try to match x86 names.
- Read through the spec's commentary and look for others.

**Comment by josharian** [comment]
cc @cherrymui

**Comment by prattmic** [comment]
All issues should be re-opened upstream if still relevant (unlikely).
