### ISSUE TITLE
cmd/asm: review assembly instruction argument order and names

### ISSUE THREAD

**Issue by josharian** [riscv/riscv-go#5]
At the least, the order of inputs to `LUI` is wrong. Once we're convinced we have pretty good coverage, it'd be good to review all the instructions and make sure we're happy with them. And--in a first for the Go assembler--document them!

**Comment by josharian** [comment]
cc @cherrymui

**Comment by prattmic** [comment]
All issues should be re-opened upstream if still relevant (unlikely).
