### ISSUE TITLE
obj.As requires int32 with RISC-V

### ISSUE THREAD

**Issue by prattmic** [riscv/riscv-go#6]
RISC-V pushes the As constants over the 16-bit limit, which forced us to upgrade obj.As to int32. It would be nice to get back to int16.

**Comment by josharian** [comment]
Upstream CLs [24222](https://go-review.googlesource.com/24222) and [24223](https://go-review.googlesource.com/24223) are ready to fix this upstream when Go 1.8 opens. When they land, we should also revert the [sizeof test fix](https://review.gerrithub.io/280868).

**Comment by josharian** [comment]
The upstream fix for this (https://go-review.googlesource.com/#/c/24223/) has gone in.

**Comment by josharian** [comment]
(Leaving just a merge and the reversion to int16 here.)

**Comment by prattmic** [comment]
I'm planning to do a merge tonight. I actually did one yesterday, but then
found I messed up gen
