### ISSUE TITLE
cmd/internal/obj/riscv: document how to regenerate inst.go

### ISSUE THREAD

**Issue by josharian** [riscv/riscv-go#7]
inst.go says "// Automatically generated by parse-opcodes". It looks like parse-opcodes is probably https://github.com/riscv/riscv-opcodes, but I don't see a Go code generator there. At a minimum, we should document how to re-generate the file (including fixing https://github.com/riscv/riscv-opcodes/issues/6).

Better would be if https://github.com/riscv/riscv-opcodes/issues/7 got fixed, at which point the json and generation script could live in this repo, where it could be easily modified and re-run by developers, and where changes to both script and json would be tracked and code reviewed.

cc @bbarenblat  (I don't seem to have github permissions to assign issues)

**Comment by josharian** [comment]
I see now that there's a PR against riscv-opcodes, and that riscv-opcodes contains reasonably parseable data files. I'd like to suggest that we (a) copy those data files into the riscv-go tree, (b) move the generation script into the riscv-go tree, and (c) make the generation script Go-specific. I'm happy to help with the legwork on that, pending feedback.

**Comment by josharian** [comment]
cc @cherrymui

**Comment by prattmic** [comment]
All issues should be re-opened upstream if still relevant (unlikely).
