### ISSUE TITLE
FP register is broken

### ISSUE THREAD

**Issue by prattmic** [riscv/riscv-go#8]
Right now we assign REG_FP = REG_S0, though it is never initialized or updated, so attempts to use it segfault. Taking a quick look at the rest of the toolchain, it looks like other arches might actually treat it as a psuedo register that doesn't have a real assignment at all?

**Comment by josharian** [comment]
Yes, references to FP get translated into offset references to SP. We should probably remove the REG_FP designation and do the FP->SP rewrites.
