### ISSUE TITLE
doc/asm: add risc-v details

### ISSUE THREAD

**Issue by josharian** [riscv/riscv-go#9]
Reminder for later, once everything has stabilized.

Quoting/modifying https://github.com/golang/go/issues/16362:

> The assembler document has a section at the end summarizing architecture-dependent details.It needs one for the new RISC-V port.

**Comment by josharian** [comment]
cc @cherrymui

**Comment by prattmic** [comment]
All issues should be re-opened upstream if still relevant (unlikely).
